server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/customer
    username: rownak
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.postgreSQLDialect
        format_sql:
    show-sql: true
  main:
    web-application-type: servlet

